import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Midnight Tears Pillow Spray',
    description: 'A haunting blend of lavender and bergamot for restless souls',
    price: 24.99,
    image: '/images/pillow-spray-placeholder.svg',
    category: 'pillow-sprays',
    isSoldOut: true,
  },
  {
    id: '2',
    name: 'Broken Heart Wax Melt',
    description: 'Rose and vanilla scented wax melts for melancholic moments',
    price: 18.99,
    image: '/images/wax-melt-placeholder.svg',
    category: 'wax-melts',
    isSoldOut: true,
  },
  {
    id: '3',
    name: 'Emo Kid Print',
    description: 'Vintage-inspired print celebrating the emo aesthetic',
    price: 29.99,
    image: '/images/print-placeholder.svg',
    category: 'prints',
    isSoldOut: true,
  },
  {
    id: '4',
    name: 'Dark Romance Pillow Spray',
    description: 'Jasmine and sandalwood for dreamy nights',
    price: 26.99,
    image: '/images/pillow-spray-placeholder.svg',
    category: 'pillow-sprays',
    isSoldOut: true,
  },
  {
    id: '5',
    name: 'Gothic Garden Wax Melt',
    description: 'Patchouli and rose for mysterious vibes',
    price: 19.99,
    image: '/images/wax-melt-placeholder.svg',
    category: 'wax-melts',
    isSoldOut: true,
  },
  {
    id: '6',
    name: 'Forever February Print',
    description: 'Custom artwork featuring our signature logo',
    price: 34.99,
    image: '/images/print-placeholder.svg',
    category: 'prints',
    isSoldOut: true,
  },
  {
    id: '7',
    name: 'Midnight Dreams Pillow Spray',
    description: 'Lavender and chamomile for peaceful sleep',
    price: 22.99,
    image: '/images/pillow-spray-placeholder.svg',
    category: 'pillow-sprays',
    isSoldOut: true,
  },
  {
    id: '8',
    name: 'Gothic Romance Wax Melt',
    description: 'Dark rose and amber for mysterious nights',
    price: 21.99,
    image: '/images/wax-melt-placeholder.svg',
    category: 'wax-melts',
    isSoldOut: true,
  },
  {
    id: '9',
    name: 'Emo Vibes Print',
    description: 'Hand-drawn artwork celebrating emo culture',
    price: 32.99,
    image: '/images/print-placeholder.svg',
    category: 'prints',
    isSoldOut: true,
  },
  {
    id: '10',
    name: 'Broken Heart Pillow Spray',
    description: 'Rose and vanilla for healing moments',
    price: 25.99,
    image: '/images/pillow-spray-placeholder.svg',
    category: 'pillow-sprays',
    isSoldOut: true,
  },
  {
    id: '11',
    name: 'Dark Angel Wax Melt',
    description: 'Jasmine and sandalwood for divine dreams',
    price: 20.99,
    image: '/images/wax-melt-placeholder.svg',
    category: 'wax-melts',
    isSoldOut: true,
  },
  {
    id: '12',
    name: 'Forever February Art Print',
    description: 'Exclusive artwork featuring our signature style',
    price: 39.99,
    image: '/images/print-placeholder.svg',
    category: 'prints',
    isSoldOut: true,
  },
]
